# Generated by Django 4.1.7 on 2023-04-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulations_with_Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regulation', models.CharField(max_length=20)),
                ('Lower_limit', models.IntegerField()),
                ('Upper_limit', models.IntegerField()),
                ('Grades', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Revaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_type', models.CharField(max_length=100)),
                ('Hallticket', models.CharField(max_length=20)),
                ('Student_Name', models.CharField(max_length=250)),
                ('Subject_code', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=200)),
                ('Mobile', models.CharField(max_length=10)),
                ('Dhondi_id', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Internal_marks', models.IntegerField()),
                ('External_marks', models.IntegerField()),
                ('Credits', models.IntegerField()),
                ('Grades', models.CharField(max_length=2)),
                ('Revaluation_Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Revaluation_copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hallticket', models.CharField(max_length=20)),
                ('Student_Name', models.CharField(max_length=250)),
                ('Subject_code', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=200)),
                ('Internal_marks', models.IntegerField()),
                ('External_marks', models.IntegerField()),
                ('Second_evaluation', models.IntegerField(blank=True, null=True)),
                ('Third_evaluation', models.IntegerField(blank=True, null=True)),
                ('Credits', models.IntegerField()),
                ('Grades', models.CharField(max_length=2)),
                ('Revaluation_Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_max_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_codes', models.CharField(max_length=50)),
                ('Subjects', models.CharField(max_length=50)),
                ('Brach_code', models.CharField(max_length=20)),
                ('Max_marks', models.IntegerField()),
                ('Max_Total_marks', models.IntegerField()),
                ('Min_marks', models.IntegerField()),
                ('Min_Total_marks', models.IntegerField()),
                ('Credit', models.IntegerField()),
                ('Subject_type', models.IntegerField()),
            ],
        ),
    ]
