# Generated by Django 4.1.7 on 2023-05-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_max_marks',
            old_name='Brach_code',
            new_name='branch_code',
        ),
        migrations.RenameField(
            model_name='subject_max_marks',
            old_name='Credit',
            new_name='credits',
        ),
        migrations.RenameField(
            model_name='subject_max_marks',
            old_name='Max_Total_marks',
            new_name='max_external_marks',
        ),
        migrations.RenameField(
            model_name='subject_max_marks',
            old_name='Max_internal',
            new_name='max_total_marks',
        ),
        migrations.RenameField(
            model_name='subject_max_marks',
            old_name='Max_marks',
            new_name='pass_external_marks',
        ),
        migrations.RenameField(
            model_name='subject_max_marks',
            old_name='Min_external',
            new_name='pass_total_marks',
        ),
        migrations.RenameField(
            model_name='subject_max_marks',
            old_name='Subject_codes',
            new_name='subject_code',
        ),
        migrations.RenameField(
            model_name='subject_max_marks',
            old_name='Subjects',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='subject_max_marks',
            old_name='Subject_type',
            new_name='subject_type',
        ),
    ]
