# Generated by Django 4.1.7 on 2023-04-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rev', '0002_remove_revaluation_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revaluation_copy',
            name='Credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revaluation_copy',
            name='External_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revaluation_copy',
            name='Grades',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='revaluation_copy',
            name='Internal_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
