# Generated by Django 4.1.7 on 2023-05-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rev', '0002_rename_brach_code_subject_max_marks_branch_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revaluation',
            name='Dhondi_id',
            field=models.CharField(max_length=20),
        ),
    ]
