# Generated by Django 4.1.7 on 2023-04-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rev', '0003_alter_revaluation_copy_credits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_max_marks',
            old_name='Min_Total_marks',
            new_name='Max_internal',
        ),
        migrations.RenameField(
            model_name='subject_max_marks',
            old_name='Min_marks',
            new_name='Min_external',
        ),
    ]
