# Generated by Django 4.1.7 on 2023-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rev', '0003_alter_revaluation_dhondi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='revaluation_copy',
            name='Total_after_revaluation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
