# Generated by Django 4.1.7 on 2023-04-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rev', '0006_remove_revaluation_second_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revaluation_copy',
            name='Revaluation_Status',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
